apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kuard
    version: "2"
  name: kuard-intruso

spec:
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:green
    ports:
      - containerPort: 8080
  