apiVersion: v1
kind: Service
metadata:
  name: nodequeue
  labels:
    app: work-queue
    component: queue
    chapter: jobs
spec:
  type: NodePort
  selector:
    app: work-queue
    component: queue
  ports:
  - port: 8080
    nodePort: 30000
    


